name: Update gh-pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout sources 🔰
      uses: actions/checkout@v2

    - name: Setup Node.js 16 🧮
      uses: actions/setup-node@v1
      with:
        node-version: 16

    - name: Cache Node.js modules 💾
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.OS }}-node-
          ${{ runner.OS }}-

    - name: Install Calibre 🧰
      run: sudo apt-get update && sudo apt install calibre

    - name: Install dependencies ⏬
      run: npm i

    - name: Build artifacts 🏗️
      run: npm run build

    - name: Get masterportal-ws version 🔖
      run: |
        echo "VERSION=$(node -pe "require('./package.json').version")" >> $GITHUB_ENV
    - name: Deploy (to docs/v${{ env.VERSION }}) 🚀
      uses: JamesIves/github-pages-deploy-action@v4.2.5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages
        folder: _book
        target-folder: v${{ env.VERSION }}

    - name: Deploy (to docs/latest) 🚀
      uses: JamesIves/github-pages-deploy-action@v4.2.5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages
        folder: _book
        target-folder: latest
